title:            Manoj's Blog
description:      writing matters
# Your site's domain goes here. Leave localhost server or blank when working locally.
url:              https://manojgautam.com.np
disqus_shortname: nix1947

# Owner/author information
owner:
  name:           Manoj Gautam
  avatar:         bio-photo.jpg
  bio:            ""
  email:           manojit.gautam@gmail.com
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter:        nix1947
  facebook:       manojgautamNEPAL
  github:         nix1947
  stackoverflow:  shining
  linkedin:       manojgautamnepal
  instagram:      manojgautami
  lastfm:
  tumblr:
  pinterest:
  foursquare:
  steam:
  dribbble:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Author(s) information
authors:
  author1:
    name:           Manoj Gautam
    avatar:         bio-photo.jpg
    bio:            "Describe your self."
    email:          manojit.gautam@gmail.com
    # Social networking links are used in author-bio sidebar. Update and remove as you like.
    twitter:        nix1947
    facebook:       manojgautamnepal
    github:         nix1947
    stackoverflow:  shining
    linkedin:       manojgautamnepal    
    instagram:      manojgautami
    lastfm:
    tumblr:
    pinterest:
    foursquare:
    steam:
    dribbble:
    # For Google Authorship https://plus.google.com/authorship
    google_plus:
 


# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about/
  - title: Posts
    url: /posts/
  - title: Courses
    url: /courses/
  - title: Resume
    url: //manojgautam.com.np/images/resume.pdf/
    external: true
 

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Kathmandu
future:      true
pygments:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
