source 'https://rubygems.org'

gem 'jekyll', '~> 3.7', '>= 3.7.2'
gem 'kramdown'
gem 'coderay'
gem 'rake'
gem 'thor'
gem 'activesupport'
gem 'stringex'
gem 'pygments.rb', '~> 1.2', '>= 1.2.1'
gem 'jekyll-gist', '~> 1.5'
